import Head from "next/head";
import { Inter } from "next/font/google";
import { Box, useMediaQuery } from "@mui/material";
import { useTheme } from "@mui/material/styles";

import { themedStyles } from "@/theme/themeStyles";
import NavDrawer from "@/components/NavDrawer";
import SearchField from "@/components/SearchField";

const inter = Inter({ subsets: ["latin"] }) as unknown as string;

export default function Home() {
  const theme = useTheme();
  const lessThan320 = useMediaQuery(theme.breakpoints.down("mobileS"));
  const lessThan425 = useMediaQuery(theme.breakpoints.down("mobileL"));

  const responsiveDrawerWidth = lessThan320
    ? theme.typography.pxToRem(60)
    : lessThan425
    ? theme.typography.pxToRem(80)
    : theme.typography.pxToRem(120);

  return (
    <>
      <Head>
        <title>Lyriks Music Playlist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href={inter} rel="stylesheet" />
      </Head>
      <main>
        <NavDrawer responsiveDrawerWidth={responsiveDrawerWidth} />
        <Box
          mt={2}
          style={{
            ...themedStyles(theme, {responsiveDrawerWidth}).content,
            ...themedStyles(theme, {responsiveDrawerWidth}).contentShift,
          }}
        >
          <SearchField lessThan425={lessThan425} />
        </Box>
      </main>
    </>
  );
}
