import Head from "next/head";
import { Inter } from "next/font/google";
import { Box, useMediaQuery } from "@mui/material";
import { useTheme } from "@mui/material/styles";

import { themedStyles } from "@/theme/themeStyles";
import NavDrawer from "@/components/NavDrawer";
import SearchField from "@/components/SearchField";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const theme = useTheme();
  const greaterThan425 = useMediaQuery(theme.breakpoints.up("mobileL"));
  const drawerWidth = 120;
  const responsiveDrawerWidth = greaterThan425 ? drawerWidth : drawerWidth - 40;

  return (
    <>
      <Head>
        <title>Lyriks Music Playlist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavDrawer responsiveDrawerWidth={responsiveDrawerWidth} />
        <Box
          mt={2}
          style={{
            ...themedStyles(theme, responsiveDrawerWidth).content,
            ...themedStyles(theme, responsiveDrawerWidth).contentShift,
          }}
        >
          <SearchField />
        </Box>
      </main>
    </>
  );
}
